build: 'off'
environment:
  matrix:
    - nodejs_version: '4'
    - nodejs_version: '5'
    - nodejs_version: '6'
install:
  - ps: 'Install-Product node $env:nodejs_version'
  - npm install npm@3.3.6 -g
  - ps: '$env:path = $env:appdata + "\npm;" + $env:path'
  - npm install
test_script:
  - node --version
  - npm --version
  - npm test
cache:
  - node_modules
